### PR TITLE
Fix for preselected rows

### PR DESCRIPTION
**Pull request by gururise**
This fix indexes preSelectedRow index correctly and thus fixes issue #207

### CODE REVIEW

**Review by minh-v — APPROVED** [review]
Nice

**Comment by chrda81** [comment]
Any news, when a new version is released with this fix?

**Comment by SubaruSpirit** [comment]
Is this fix in any of the releases? I'm currently using 0.3.4.post3, and pre_selected_rows is not working

**Comment by gururise** [comment]
Seems like this project may be dead. I've created a pypi package with this fix here: 
https://pypi.org/project/streamlit-aggrid-bugfix/

**Comment by hansthen** [comment]
Thanks for merging the fix. Any idea when a new version will be released to pypi?

**Comment by algorni** [comment]
> Is this fix in any of the releases? I'm currently using 0.3.4.post3, and pre_selected_rows is not working

same here

**Comment by tansaku** [comment]
I appear to be on         "streamlit-aggrid": "version": "==1.0.5" and pre_selected_rows not working for me either ... :-(

**Pull request closed without merging**
