### PR TITLE
Fix issue with st.tabs where grids on inactive tabs disappear

### PR DESCRIPTION
**Pull request by broccoliboy**
Grids on inactive tabs get updated to height=0 when app reruns. Sometimes they update when switching to the tab they reside on, sometimes not. I saw inconsistent behavior depending on normal vs wide mode in settings. This PR seems to solve the issue on both. See #159

### CODE REVIEW

**Comment by broccoliboy** [comment]
Auto column sizing still does not work properly. Working on a fix for this...

**Comment by broccoliboy** [comment]
Fixed issue with auto column width. Use gridOptions.suppressColumnVirtualisation=True for relatively small grids for proper column sizing. See https://www.ag-grid.com/javascript-data-grid/column-sizing/#auto-size-columns for details on column sizing limitations with virtualization.

**Comment by broccoliboy** [comment]
Fixed clipping on last column and bottom of table

**Comment by broccoliboy** [comment]
Updated to use ag-grid gridSizeChanged event for all resizing needs

**Comment by broccoliboy** [comment]
Hi @Quajijalon, please see [this comment](https://github.com/PablocFonseca/streamlit-aggrid/issues/159#issuecomment-1527708907) for instructions on building the frontend.

**Comment by uriyacovy** [comment]
@broccoliboy , @PablocFonseca,
The fix is working great for me (after manually building) on three different platforms (Ubuntu, windows 10 & 11).
I'd be glad this this can be pulled to the official release.

**Pull request merged**
